### ISSUE TITLE
Problem displaying 9 and : (Browser related)

### ISSUE THREAD

**Issue by robzed** [tabemann/zeptocomjs#1]
Hi,

There is a weird problem with browsers not displaying 9 and : properly. The fix is to switch the default fonts:

For example: https://support.mozilla.org/en-US/questions/1269532

In `zeptocom.js` case, this is fixed in the EDIT tabs by Monospace - "Change from Courier (or other fixed-pitch font) to Courier New". 

![image](https://github.com/tabemann/zeptocomjs/assets/4871013/092a9347-dc26-4442-9839-31591cf22147)

But it doesn't appears to be fixed in the Terminal Window...

![image](https://github.com/tabemann/zeptocomjs/assets/4871013/fd5e04f7-830c-432a-a0aa-ecf42ef1a696)

Any ideas?

**Comment by tabemann** [comment]
I just changed zeptocom.js to use the current 'monospace' font for the terminal rather than the default used by xterm.js, which it uses internally. I also updated the hosted zeptocom.js at https://tabemann.github.io/zeptocomjs/zeptocom.html to use this (and confirmed that it is now up on the site). This should solve your issues ─ let me know if you still have problems with this.

**Comment by robzed** [comment]
Well tested - this fixes the issue.
