### ISSUE TITLE
RP2350 Pico 2 USB connection is very unstable

### ISSUE THREAD

**Issue by veryalien** [tabemann/zeptocomjs#4]
I have both rp2040 pico and rp2350 pico 2 boards. The connection is rock solid when using zeptocomjs with the rp2040.
When I use the pico 2 rp2350 it won't allow me to send 'large' files, it keeps 'hanging' the connection during the transfer, it just freezes and doesn't seem to come back.
By the way, exactly the same setup as for the rp2040 pico, I just replace it with the pico 2, I'm using the same ubuntu laptop, usb port, cable, and breadboard.
This makes working with zeptocomjs very difficult or nearly impossible.
I can use the zeptocomjs console, for entering commands, etc., but data transfer doesn't seem reliable.
Any ideas?

**Comment by tabemann** [comment]
On Fri, Sep 13, 2024 at 8:55 AM veryalien ***@***.***> wrote:

> I have both rp2040 pico and rp2350 pico 2 boards. The connection is rock
> solid when using zeptocomjs with the rp2040.
> When I use the pico 2 rp2350 it won't allow me to send 'large' files, it
> keeps dropping the connection during the transfer.
> By the way, exactly the same setup as for the rp2040 pico, I just replace
> it with the pico 2, I'm using the same ubuntu laptop, usb port, cable, and
> breadboard.
> This makes working with zeptocomjs very difficult or nearly impossible.
> I can use the console, for entering commands, etc., but data transfer
> doesn't seem reliable.
> Any ideas?
>
I have noticed on very occasional instances noticed failures when uploading
with the RP2350 using utils/codeload.sh, but usually I have no problem with
things like uploading zeptoed, and extra/common/zeptoed.fs is a pretty
large source file. This seems odd to me, because the source code for USB on
the RP2350 and RP2040 is practically identical (the only changes being that
the RP2350 uses different base addresses, and that I had to add extra code
for cleanup prior to rebooting due to issues with locking up the USB
connection on reboot due to differences in how rebooting is done on the
RP2350 vis-a-vis the RP2040). I will take a look at this.

Travis

**Comment by tabemann** [comment]
On Fri, Sep 13, 2024 at 9:57 AM Travis Bemann ***@***.***> wrote:

> On Fri, Sep 13, 2024 at 8:55 AM veryalien ***@***.***>
> wrote:
>
>> I have both rp2040 pico and rp2350 pico 2 boards. The connection is rock
>> solid when using zeptocomjs with the rp2040.
>> When I use the pico 2 rp2350 it won't allow me to send 'large' files, it
>> keeps dropping the connection during the transfer.
>> By the way, exactly the same setup as for the rp2040 pico, I just replace
>> it with the pico 2, I'm using the same ubuntu laptop, usb port, cable, and
>> breadboard.
>> This makes working with zeptocomjs very difficult or nearly impossible.
>> I can use the console, for entering commands, etc., but data transfer
>> doesn't seem reliable.
>> Any ideas?
>>
> I have noticed on very occasional instances noticed failures when
> uploading with the RP2350 using utils/codeload.sh, but usually I have no
> problem with things like uploading zeptoed, and extra/common/zeptoed.fs is
> a pretty large source file. This seems odd to me, because the source code
> for USB on the RP2350 and RP2040 is practically identical (the only changes
> being that the RP2350 uses different base addresses, and that I had to add
> extra code for cleanup prior to rebooting due to issues with locking up the
> USB connection on reboot due to differences in how rebooting is done on the
> RP2350 vis-a-vis the RP2040). I will take a look at this.
>

Okay, this is very interesting, because in my initial testing it breaks
completely when using zeptocom.js but works fine the vast majority of the
time when using utils/codeload3.sh, which is what I have been using lately
hence why I missed this. This raises the question of *why* this is not
working with zeptocom.js with the RP2350, particularly because there
supposedly aren't any differences between USB on the RP2040 and the RP2350.
Thank you for bringing this up, as I would have otherwise missed it!

Travis

**Comment by tabemann** [comment]
On Fri, Sep 13, 2024 at 11:54 AM Travis Bemann ***@***.***> wrote:

> On Fri, Sep 13, 2024 at 9:57 AM Travis Bemann ***@***.***> wrote:
>
>> On Fri, Sep 13, 2024 at 8:55 AM veryalien ***@***.***>
>> wrote:
>>
>>> I have both rp2040 pico and rp2350 pico 2 boards. The connection is rock
>>> solid when using zeptocomjs with the rp2040.
>>> When I use the pico 2 rp2350 it won't allow me to send 'large' files, it
>>> keeps dropping the connection during the transfer.
>>> By the way, exactly the same setup as for the rp2040 pico, I just
>>> replace it with the pico 2, I'm using the same ubuntu laptop, usb port,
>>> cable, and breadboard.
>>> This makes working with zeptocomjs very difficult or nearly impossible.
>>> I can use the console, for entering commands, etc., but data transfer
>>> doesn't seem reliable.
>>> Any ideas?
>>>
>> I have noticed on very occasional instances noticed failures when
>> uploading with the RP2350 using utils/codeload.sh, but usually I have no
>> problem with things like uploading zeptoed, and extra/common/zeptoed.fs is
>> a pretty large source file. This seems odd to me, because the source code
>> for USB on the RP2350 and RP2040 is practically identical (the only changes
>> being that the RP2350 uses different base addresses, and that I had to add
>> extra code for cleanup prior to rebooting due to issues with locking up the
>> USB connection on reboot due to differences in how rebooting is done on the
>> RP2350 vis-a-vis the RP2040). I will take a look at this.
>>
>
> Okay, this is very interesting, because in my initial testing it breaks
> completely when using zeptocom.js but works fine the vast majority of the
> time when using utils/codeload3.sh, which is what I have been using lately
> hence why I missed this. This raises the question of *why* this is not
> working with zeptocom.js with the RP2350, particularly because there
> supposedly aren't any differences between USB on the RP2040 and the RP2350.
> Thank you for bringing this up, as I would have otherwise missed it!
>

The problem seems to be Chrome's fault, but I don't know why it is only
affecting the RP2350 (maybe the RP2350 being faster is breaking things?). I
made a hack to zeptocom.js which seems to make the problem go away the vast
majority of the time, which is to shrink the buffer used by WebSerial from
65535 bytes to a mere 16 bytes. See if this works now. (There is also a bug
in zeptoforth that affects long lines of input, but that seems unrelated,
and will be fixed in the next beta release, or now if you feel like
building the rp2350 branch of zeptoforth yourself.)

Travis

**Comment by veryalien** [comment]
It seems to work very reliably now with the latest version.
For me, it's fixed, even if the real cause with the rp2350, or Chrome, is unknown.
